apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
  name: amq-broker-demo-simple
  application: amq-broker-demo-app-simple
spec:
  version: 7.6.0
  adminUser: amq-demo-user
  adminPassword: password
  deploymentPlan:
    size: 1
    image: registry.redhat.io/amq7/amq-broker:7.6
    requireLogin: false
    persistenceEnabled: false
    journalType: nio
    messageMigration: false
  console:
    expose: true
  acceptors:
    - name: svcport
      protocols: amqp
      port: 5672
      expose: true
#      anycastPrefix: jms.topic.
#      multicastPrefix: jms.topic.
      connectionsAllowed: 100
      sslEnabled: true
      sslSecret: amq-broker-amqp-secret
      enabledProtocols: TLSv1.2
      needClientAuth: false
  connectors:
    - name: connector0
      host: localhost
      port: 22222
      expose: false
  upgrades:
      enabled: false
      minor: false

